/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.supervisor.DashboardSupervisorVistoria;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgar
 */
public class AlterarStatus extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarStatus
     */
    public AlterarStatus() {
        initComponents();
        PainelVistoriaEncontrada.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodVistoriaInformado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        PainelVistoriaEncontrada = new javax.swing.JPanel();
        btnVistoriaAgendada = new javax.swing.JButton();
        btnVistoriaRealizada = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Visoria Desejada"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Selecione a Vistoria que deseja alterar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código da Vistoria");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-localizar-e-substituir-30.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(txtCodVistoriaInformado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodVistoriaInformado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        PainelVistoriaEncontrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Status"));

        btnVistoriaAgendada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-hora-extra-48.png"))); // NOI18N
        btnVistoriaAgendada.setText("Vistoria Agendada");
        btnVistoriaAgendada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistoriaAgendadaActionPerformed(evt);
            }
        });

        btnVistoriaRealizada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-ok-48.png"))); // NOI18N
        btnVistoriaRealizada.setText("Vistoria Realizada");
        btnVistoriaRealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistoriaRealizadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelVistoriaEncontradaLayout = new javax.swing.GroupLayout(PainelVistoriaEncontrada);
        PainelVistoriaEncontrada.setLayout(PainelVistoriaEncontradaLayout);
        PainelVistoriaEncontradaLayout.setHorizontalGroup(
            PainelVistoriaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVistoriaEncontradaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnVistoriaAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVistoriaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        PainelVistoriaEncontradaLayout.setVerticalGroup(
            PainelVistoriaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVistoriaEncontradaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PainelVistoriaEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistoriaAgendada)
                    .addComponent(btnVistoriaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelVistoriaEncontrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelVistoriaEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(txtCodVistoriaInformado.getText().equals("ok")){
            PainelVistoriaEncontrada.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Não há vistoria com o código informado", "Vistoria Não Encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVistoriaAgendadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistoriaAgendadaActionPerformed
        AgendarData tela = new AgendarData();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVistoriaAgendadaActionPerformed

    private void btnVistoriaRealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistoriaRealizadaActionPerformed
        ConfirmarVistoria tela = new ConfirmarVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVistoriaRealizadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelVistoriaEncontrada;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVistoriaAgendada;
    private javax.swing.JButton btnVistoriaRealizada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodVistoriaInformado;
    // End of variables declaration//GEN-END:variables
}
