/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.Protocolador.DashboardProtocolador;
import gui.supervisor.DashboardSupervisorVistoria;

/**
 *
 * @author Edgar
 */
public class SituacoesVistoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form SituacoesVistoria
     */
    public SituacoesVistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTodasVistorias = new javax.swing.JButton();
        btnVistoriaAgendada = new javax.swing.JButton();
        btnVistoriasRealizadas = new javax.swing.JButton();
        btnVistoriaSolicitada = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        btnTodasVistorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTodasVistorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-selecionar-tudo-48.png"))); // NOI18N
        btnTodasVistorias.setText("Todas Vistorias");
        btnTodasVistorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasVistoriasActionPerformed(evt);
            }
        });

        btnVistoriaAgendada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVistoriaAgendada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-planejamento-de-tarefas-48.png"))); // NOI18N
        btnVistoriaAgendada.setText("Vistorias Agendadas");
        btnVistoriaAgendada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistoriaAgendadaActionPerformed(evt);
            }
        });

        btnVistoriasRealizadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVistoriasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-verificar-todos-os-48.png"))); // NOI18N
        btnVistoriasRealizadas.setText("Vistorias Realizadas");
        btnVistoriasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistoriasRealizadasActionPerformed(evt);
            }
        });

        btnVistoriaSolicitada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVistoriaSolicitada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-telefone-a-chamar-48.png"))); // NOI18N
        btnVistoriaSolicitada.setText("Vistorias Não Agendadas");
        btnVistoriaSolicitada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistoriaSolicitadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVistoriaSolicitada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVistoriaAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVistoriasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTodasVistorias)
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btnTodasVistorias, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistoriaSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVistoriaAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVistoriasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodasVistoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasVistoriasActionPerformed
        TodasVistorias tela = new TodasVistorias();
        try{
            DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
            tela.setVisible(true);
        }catch(NullPointerException er){
            DashboardProtocolador.DesktopPaneProtocolador.add(tela);
            tela.setVisible(true);
        }
        
    }//GEN-LAST:event_btnTodasVistoriasActionPerformed

    private void btnVistoriaAgendadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistoriaAgendadaActionPerformed
        VistoriasAgendadas tela = new VistoriasAgendadas();
        
        try{
            DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
            tela.setVisible(true);
        }catch(NullPointerException er){
            DashboardProtocolador.DesktopPaneProtocolador.add(tela);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_btnVistoriaAgendadaActionPerformed

    private void btnVistoriasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistoriasRealizadasActionPerformed
        VistoriaRealizadas tela = new VistoriaRealizadas();
        
        try{
            DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
            tela.setVisible(true);
        }catch(NullPointerException er){
            DashboardProtocolador.DesktopPaneProtocolador.add(tela);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_btnVistoriasRealizadasActionPerformed

    private void btnVistoriaSolicitadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistoriaSolicitadaActionPerformed
        VistoriasNaoAgendadas tela = new VistoriasNaoAgendadas();
        
        try{
            DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
            tela.setVisible(true);
        }catch(NullPointerException er){
            DashboardProtocolador.DesktopPaneProtocolador.add(tela);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_btnVistoriaSolicitadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTodasVistorias;
    private javax.swing.JButton btnVistoriaAgendada;
    private javax.swing.JButton btnVistoriaSolicitada;
    private javax.swing.JButton btnVistoriasRealizadas;
    // End of variables declaration//GEN-END:variables
}
