/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.supervisor;
import gui.AgendarVistoria;
import gui.AlterarStatus;
import gui.ApagarVistoria;
//import static gui.Dashboard.desktopPaneDashBoard;
import gui.LocalizarVistoria;
import gui.SituacoesVistoria;
import gui.TodasVistorias;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author Edgar
 */
public class DashboardSupervisorVistoria extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardSupervisorVistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icone = new ImageIcon(getClass().getResource("/imagens/dashbordVistoria.jpg"));
        Image imagem = icone.getImage();
        desktopPaneDashBoard = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics gra){
                gra.drawImage(imagem, 0, 0, getWidth(), getHeight(), this);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MenuItemLogout = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        Vsitoria = new javax.swing.JMenu();
        MenuItem_AgendarVisotira = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuItem_AltVistoria = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItem_ConsultarVistorias = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItem_AlterarStatus = new javax.swing.JMenuItem();
        MenuItemApagarVistoria = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneDashBoardLayout = new javax.swing.GroupLayout(desktopPaneDashBoard);
        desktopPaneDashBoard.setLayout(desktopPaneDashBoardLayout);
        desktopPaneDashBoardLayout.setHorizontalGroup(
            desktopPaneDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        desktopPaneDashBoardLayout.setVerticalGroup(
            desktopPaneDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Acesso");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-alterar-usuário-masculino-40.png"))); // NOI18N
        MenuItemLogout.setMnemonic('a');
        MenuItemLogout.setText("Logout");
        fileMenu.add(MenuItemLogout);

        MenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-logout-arredondado-40.png"))); // NOI18N
        MenuItemExit.setMnemonic('x');
        MenuItemExit.setText("Sair");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(MenuItemExit);

        menuBar.add(fileMenu);

        Vsitoria.setMnemonic('e');
        Vsitoria.setText("Vistoria");
        Vsitoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Vsitoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VsitoriaActionPerformed(evt);
            }
        });

        MenuItem_AgendarVisotira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-lista-restrita-20.png"))); // NOI18N
        MenuItem_AgendarVisotira.setMnemonic('t');
        MenuItem_AgendarVisotira.setText("Agendar Vistoria");
        MenuItem_AgendarVisotira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AgendarVisotiraActionPerformed(evt);
            }
        });
        Vsitoria.add(MenuItem_AgendarVisotira);
        Vsitoria.add(jSeparator2);

        MenuItem_AltVistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-alterar-20.png"))); // NOI18N
        MenuItem_AltVistoria.setMnemonic('y');
        MenuItem_AltVistoria.setText("Alterar Dados de Vistoria");
        MenuItem_AltVistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AltVistoriaActionPerformed(evt);
            }
        });
        Vsitoria.add(MenuItem_AltVistoria);
        Vsitoria.add(jSeparator3);

        MenuItem_ConsultarVistorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mais-zoom-20.png"))); // NOI18N
        MenuItem_ConsultarVistorias.setMnemonic('p');
        MenuItem_ConsultarVistorias.setText("Consultar Vistorias");
        MenuItem_ConsultarVistorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ConsultarVistoriasActionPerformed(evt);
            }
        });
        Vsitoria.add(MenuItem_ConsultarVistorias);
        Vsitoria.add(jSeparator1);

        MenuItem_AlterarStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-à-fazer-20.png"))); // NOI18N
        MenuItem_AlterarStatus.setMnemonic('d');
        MenuItem_AlterarStatus.setText("Alterar Status De Vistoria");
        MenuItem_AlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_AlterarStatusActionPerformed(evt);
            }
        });
        Vsitoria.add(MenuItem_AlterarStatus);

        MenuItemApagarVistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-apagar-para-sempre-20.png"))); // NOI18N
        MenuItemApagarVistoria.setText("Apagar Vistoria");
        MenuItemApagarVistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemApagarVistoriaActionPerformed(evt);
            }
        });
        Vsitoria.add(MenuItemApagarVistoria);

        menuBar.add(Vsitoria);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneDashBoard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneDashBoard)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void VsitoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VsitoriaActionPerformed
        /*ApagarVistoria tela = new ApagarVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
        */
    }//GEN-LAST:event_VsitoriaActionPerformed

    private void MenuItem_AgendarVisotiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AgendarVisotiraActionPerformed
        AgendarVistoria tela = new AgendarVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuItem_AgendarVisotiraActionPerformed

    private void MenuItem_ConsultarVistoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ConsultarVistoriasActionPerformed
        SituacoesVistoria tela = new SituacoesVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuItem_ConsultarVistoriasActionPerformed

    private void MenuItem_AltVistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AltVistoriaActionPerformed
        LocalizarVistoria tela = new LocalizarVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
        
    }//GEN-LAST:event_MenuItem_AltVistoriaActionPerformed

    private void MenuItem_AlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_AlterarStatusActionPerformed
        AlterarStatus tela = new AlterarStatus();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuItem_AlterarStatusActionPerformed

    private void MenuItemApagarVistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemApagarVistoriaActionPerformed
        ApagarVistoria tela = new ApagarVistoria();
        
        DashboardSupervisorVistoria.desktopPaneDashBoard.add(tela);
        
        tela.setVisible(true);
    }//GEN-LAST:event_MenuItemApagarVistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardSupervisorVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardSupervisorVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardSupervisorVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardSupervisorVistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardSupervisorVistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemApagarVistoria;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemLogout;
    private javax.swing.JMenuItem MenuItem_AgendarVisotira;
    private javax.swing.JMenuItem MenuItem_AltVistoria;
    private javax.swing.JMenuItem MenuItem_AlterarStatus;
    private javax.swing.JMenuItem MenuItem_ConsultarVistorias;
    private javax.swing.JMenu Vsitoria;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane desktopPaneDashBoard;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
